site_name: kopimi.datapor.no
theme: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.tabs
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx.inline
  - pymdownx.superfences